name: Actions build dongshanpi seven build  images.

on:
  push:
    branches:
      - main
jobs:
  build-all:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config: [dongshanpiserven_core_defconfig ]
    steps:
      - uses: actions/checkout@v2
        with:
          path: buildroot-external-st
      - uses: actions/checkout@v2
        with:
          repository: bootlin/buildroot
          ref: st/2021.02
          path: buildroot
      - name: Install buildroot dependencies
        run: sudo apt install debianutils sed make binutils build-essential gcc g++ bash patch gzip bzip2 perl tar cpio unzip rsync file bc git mtools
      - name: Configure Buildroot
        run: make -C buildroot BR2_EXTERNAL=../buildroot-external-st O=../output ${{ matrix.config }}
      - name: Build Buildroot
        run: make -C buildroot BR2_EXTERNAL=../buildroot-external-st O=../output
      - name: Run legal-info
        run: make -C buildroot BR2_EXTERNAL=../buildroot-external-st O=../output legal-info

      - name: Compress sdcard.img
        run: gzip -9 output/images/sdcard.img

      - name: Store images
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config }}
          path: output/images/sdcard.img.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output/images/sdcard.img.gz
